/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedMaisRouteImport } from './routes/_authenticated/mais'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedBiRouteImport } from './routes/_authenticated/bi'
import { Route as AuthenticatedAuraIaRouteImport } from './routes/_authenticated/aura-ia'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedWhatsappIndexRouteImport } from './routes/_authenticated/whatsapp.index'
import { Route as AuthenticatedMarketingIndexRouteImport } from './routes/_authenticated/marketing.index'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated/financeiro.index'
import { Route as AuthenticatedEquipeIndexRouteImport } from './routes/_authenticated/equipe.index'
import { Route as AuthenticatedBiIndexRouteImport } from './routes/_authenticated/bi.index'
import { Route as AuthenticatedAuraIaIndexRouteImport } from './routes/_authenticated/aura-ia.index'
import { Route as AuthenticatedWhatsappTemplatesRouteImport } from './routes/_authenticated/whatsapp.templates'
import { Route as AuthenticatedWhatsappConfigRouteImport } from './routes/_authenticated/whatsapp.config'
import { Route as AuthenticatedWhatsappIdRouteImport } from './routes/_authenticated/whatsapp.$id'
import { Route as AuthenticatedServicosIdRouteImport } from './routes/_authenticated/servicos.$id'
import { Route as AuthenticatedMarketingJornadasRouteImport } from './routes/_authenticated/marketing.jornadas'
import { Route as AuthenticatedMarketingIaRouteImport } from './routes/_authenticated/marketing.ia'
import { Route as AuthenticatedMarketingIdRouteImport } from './routes/_authenticated/marketing.$id'
import { Route as AuthenticatedFinanceiroFluxoRouteImport } from './routes/_authenticated/financeiro.fluxo'
import { Route as AuthenticatedFinanceiroCfoRouteImport } from './routes/_authenticated/financeiro.cfo'
import { Route as AuthenticatedEstoquePreditivoRouteImport } from './routes/_authenticated/estoque.preditivo'
import { Route as AuthenticatedEstoqueIdRouteImport } from './routes/_authenticated/estoque.$id'
import { Route as AuthenticatedEquipeIdRouteImport } from './routes/_authenticated/equipe.$id'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedBiServicosRouteImport } from './routes/_authenticated/bi.servicos'
import { Route as AuthenticatedBiPreditivoRouteImport } from './routes/_authenticated/bi.preditivo'
import { Route as AuthenticatedBiClientesRouteImport } from './routes/_authenticated/bi.clientes'
import { Route as AuthenticatedAuraIaConselhoRouteImport } from './routes/_authenticated/aura-ia.conselho'
import { Route as AuthenticatedAuraIaChatRouteImport } from './routes/_authenticated/aura-ia.chat'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaisRoute = AuthenticatedMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBiRoute = AuthenticatedBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuraIaRoute = AuthenticatedAuraIaRouteImport.update({
  id: '/aura-ia',
  path: '/aura-ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappIndexRoute =
  AuthenticatedWhatsappIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWhatsappRoute,
  } as any)
const AuthenticatedMarketingIndexRoute =
  AuthenticatedMarketingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedEquipeIndexRoute =
  AuthenticatedEquipeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEquipeRoute,
  } as any)
const AuthenticatedBiIndexRoute = AuthenticatedBiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedBiRoute,
} as any)
const AuthenticatedAuraIaIndexRoute =
  AuthenticatedAuraIaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAuraIaRoute,
  } as any)
const AuthenticatedWhatsappTemplatesRoute =
  AuthenticatedWhatsappTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedWhatsappRoute,
  } as any)
const AuthenticatedWhatsappConfigRoute =
  AuthenticatedWhatsappConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedWhatsappRoute,
  } as any)
const AuthenticatedWhatsappIdRoute = AuthenticatedWhatsappIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedWhatsappRoute,
} as any)
const AuthenticatedServicosIdRoute = AuthenticatedServicosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedServicosRoute,
} as any)
const AuthenticatedMarketingJornadasRoute =
  AuthenticatedMarketingJornadasRouteImport.update({
    id: '/jornadas',
    path: '/jornadas',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingIaRoute =
  AuthenticatedMarketingIaRouteImport.update({
    id: '/ia',
    path: '/ia',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingIdRoute =
  AuthenticatedMarketingIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedFinanceiroFluxoRoute =
  AuthenticatedFinanceiroFluxoRouteImport.update({
    id: '/fluxo',
    path: '/fluxo',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroCfoRoute =
  AuthenticatedFinanceiroCfoRouteImport.update({
    id: '/cfo',
    path: '/cfo',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedEstoquePreditivoRoute =
  AuthenticatedEstoquePreditivoRouteImport.update({
    id: '/preditivo',
    path: '/preditivo',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueIdRoute = AuthenticatedEstoqueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEstoqueRoute,
} as any)
const AuthenticatedEquipeIdRoute = AuthenticatedEquipeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEquipeRoute,
} as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)
const AuthenticatedBiServicosRoute = AuthenticatedBiServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedBiRoute,
} as any)
const AuthenticatedBiPreditivoRoute =
  AuthenticatedBiPreditivoRouteImport.update({
    id: '/preditivo',
    path: '/preditivo',
    getParentRoute: () => AuthenticatedBiRoute,
  } as any)
const AuthenticatedBiClientesRoute = AuthenticatedBiClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedBiRoute,
} as any)
const AuthenticatedAuraIaConselhoRoute =
  AuthenticatedAuraIaConselhoRouteImport.update({
    id: '/conselho',
    path: '/conselho',
    getParentRoute: () => AuthenticatedAuraIaRoute,
  } as any)
const AuthenticatedAuraIaChatRoute = AuthenticatedAuraIaChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAuraIaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/aura-ia': typeof AuthenticatedAuraIaRouteWithChildren
  '/bi': typeof AuthenticatedBiRouteWithChildren
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRouteWithChildren
  '/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/mais': typeof AuthenticatedMaisRoute
  '/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/servicos': typeof AuthenticatedServicosRouteWithChildren
  '/whatsapp': typeof AuthenticatedWhatsappRouteWithChildren
  '/aura-ia/chat': typeof AuthenticatedAuraIaChatRoute
  '/aura-ia/conselho': typeof AuthenticatedAuraIaConselhoRoute
  '/bi/clientes': typeof AuthenticatedBiClientesRoute
  '/bi/preditivo': typeof AuthenticatedBiPreditivoRoute
  '/bi/servicos': typeof AuthenticatedBiServicosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/equipe/$id': typeof AuthenticatedEquipeIdRoute
  '/estoque/$id': typeof AuthenticatedEstoqueIdRoute
  '/estoque/preditivo': typeof AuthenticatedEstoquePreditivoRoute
  '/financeiro/cfo': typeof AuthenticatedFinanceiroCfoRoute
  '/financeiro/fluxo': typeof AuthenticatedFinanceiroFluxoRoute
  '/marketing/$id': typeof AuthenticatedMarketingIdRoute
  '/marketing/ia': typeof AuthenticatedMarketingIaRoute
  '/marketing/jornadas': typeof AuthenticatedMarketingJornadasRoute
  '/servicos/$id': typeof AuthenticatedServicosIdRoute
  '/whatsapp/$id': typeof AuthenticatedWhatsappIdRoute
  '/whatsapp/config': typeof AuthenticatedWhatsappConfigRoute
  '/whatsapp/templates': typeof AuthenticatedWhatsappTemplatesRoute
  '/aura-ia/': typeof AuthenticatedAuraIaIndexRoute
  '/bi/': typeof AuthenticatedBiIndexRoute
  '/equipe/': typeof AuthenticatedEquipeIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/whatsapp/': typeof AuthenticatedWhatsappIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/mais': typeof AuthenticatedMaisRoute
  '/servicos': typeof AuthenticatedServicosRouteWithChildren
  '/aura-ia/chat': typeof AuthenticatedAuraIaChatRoute
  '/aura-ia/conselho': typeof AuthenticatedAuraIaConselhoRoute
  '/bi/clientes': typeof AuthenticatedBiClientesRoute
  '/bi/preditivo': typeof AuthenticatedBiPreditivoRoute
  '/bi/servicos': typeof AuthenticatedBiServicosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/equipe/$id': typeof AuthenticatedEquipeIdRoute
  '/estoque/$id': typeof AuthenticatedEstoqueIdRoute
  '/estoque/preditivo': typeof AuthenticatedEstoquePreditivoRoute
  '/financeiro/cfo': typeof AuthenticatedFinanceiroCfoRoute
  '/financeiro/fluxo': typeof AuthenticatedFinanceiroFluxoRoute
  '/marketing/$id': typeof AuthenticatedMarketingIdRoute
  '/marketing/ia': typeof AuthenticatedMarketingIaRoute
  '/marketing/jornadas': typeof AuthenticatedMarketingJornadasRoute
  '/servicos/$id': typeof AuthenticatedServicosIdRoute
  '/whatsapp/$id': typeof AuthenticatedWhatsappIdRoute
  '/whatsapp/config': typeof AuthenticatedWhatsappConfigRoute
  '/whatsapp/templates': typeof AuthenticatedWhatsappTemplatesRoute
  '/aura-ia': typeof AuthenticatedAuraIaIndexRoute
  '/bi': typeof AuthenticatedBiIndexRoute
  '/equipe': typeof AuthenticatedEquipeIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/marketing': typeof AuthenticatedMarketingIndexRoute
  '/whatsapp': typeof AuthenticatedWhatsappIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/aura-ia': typeof AuthenticatedAuraIaRouteWithChildren
  '/_authenticated/bi': typeof AuthenticatedBiRouteWithChildren
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRouteWithChildren
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/_authenticated/mais': typeof AuthenticatedMaisRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/_authenticated/servicos': typeof AuthenticatedServicosRouteWithChildren
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRouteWithChildren
  '/_authenticated/aura-ia/chat': typeof AuthenticatedAuraIaChatRoute
  '/_authenticated/aura-ia/conselho': typeof AuthenticatedAuraIaConselhoRoute
  '/_authenticated/bi/clientes': typeof AuthenticatedBiClientesRoute
  '/_authenticated/bi/preditivo': typeof AuthenticatedBiPreditivoRoute
  '/_authenticated/bi/servicos': typeof AuthenticatedBiServicosRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/equipe/$id': typeof AuthenticatedEquipeIdRoute
  '/_authenticated/estoque/$id': typeof AuthenticatedEstoqueIdRoute
  '/_authenticated/estoque/preditivo': typeof AuthenticatedEstoquePreditivoRoute
  '/_authenticated/financeiro/cfo': typeof AuthenticatedFinanceiroCfoRoute
  '/_authenticated/financeiro/fluxo': typeof AuthenticatedFinanceiroFluxoRoute
  '/_authenticated/marketing/$id': typeof AuthenticatedMarketingIdRoute
  '/_authenticated/marketing/ia': typeof AuthenticatedMarketingIaRoute
  '/_authenticated/marketing/jornadas': typeof AuthenticatedMarketingJornadasRoute
  '/_authenticated/servicos/$id': typeof AuthenticatedServicosIdRoute
  '/_authenticated/whatsapp/$id': typeof AuthenticatedWhatsappIdRoute
  '/_authenticated/whatsapp/config': typeof AuthenticatedWhatsappConfigRoute
  '/_authenticated/whatsapp/templates': typeof AuthenticatedWhatsappTemplatesRoute
  '/_authenticated/aura-ia/': typeof AuthenticatedAuraIaIndexRoute
  '/_authenticated/bi/': typeof AuthenticatedBiIndexRoute
  '/_authenticated/equipe/': typeof AuthenticatedEquipeIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/_authenticated/whatsapp/': typeof AuthenticatedWhatsappIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/agenda'
    | '/aura-ia'
    | '/bi'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/mais'
    | '/marketing'
    | '/servicos'
    | '/whatsapp'
    | '/aura-ia/chat'
    | '/aura-ia/conselho'
    | '/bi/clientes'
    | '/bi/preditivo'
    | '/bi/servicos'
    | '/clientes/$id'
    | '/equipe/$id'
    | '/estoque/$id'
    | '/estoque/preditivo'
    | '/financeiro/cfo'
    | '/financeiro/fluxo'
    | '/marketing/$id'
    | '/marketing/ia'
    | '/marketing/jornadas'
    | '/servicos/$id'
    | '/whatsapp/$id'
    | '/whatsapp/config'
    | '/whatsapp/templates'
    | '/aura-ia/'
    | '/bi/'
    | '/equipe/'
    | '/financeiro/'
    | '/marketing/'
    | '/whatsapp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/agenda'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/mais'
    | '/servicos'
    | '/aura-ia/chat'
    | '/aura-ia/conselho'
    | '/bi/clientes'
    | '/bi/preditivo'
    | '/bi/servicos'
    | '/clientes/$id'
    | '/equipe/$id'
    | '/estoque/$id'
    | '/estoque/preditivo'
    | '/financeiro/cfo'
    | '/financeiro/fluxo'
    | '/marketing/$id'
    | '/marketing/ia'
    | '/marketing/jornadas'
    | '/servicos/$id'
    | '/whatsapp/$id'
    | '/whatsapp/config'
    | '/whatsapp/templates'
    | '/aura-ia'
    | '/bi'
    | '/equipe'
    | '/financeiro'
    | '/marketing'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/portal'
    | '/_authenticated/agenda'
    | '/_authenticated/aura-ia'
    | '/_authenticated/bi'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/estoque'
    | '/_authenticated/financeiro'
    | '/_authenticated/mais'
    | '/_authenticated/marketing'
    | '/_authenticated/servicos'
    | '/_authenticated/whatsapp'
    | '/_authenticated/aura-ia/chat'
    | '/_authenticated/aura-ia/conselho'
    | '/_authenticated/bi/clientes'
    | '/_authenticated/bi/preditivo'
    | '/_authenticated/bi/servicos'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/equipe/$id'
    | '/_authenticated/estoque/$id'
    | '/_authenticated/estoque/preditivo'
    | '/_authenticated/financeiro/cfo'
    | '/_authenticated/financeiro/fluxo'
    | '/_authenticated/marketing/$id'
    | '/_authenticated/marketing/ia'
    | '/_authenticated/marketing/jornadas'
    | '/_authenticated/servicos/$id'
    | '/_authenticated/whatsapp/$id'
    | '/_authenticated/whatsapp/config'
    | '/_authenticated/whatsapp/templates'
    | '/_authenticated/aura-ia/'
    | '/_authenticated/bi/'
    | '/_authenticated/equipe/'
    | '/_authenticated/financeiro/'
    | '/_authenticated/marketing/'
    | '/_authenticated/whatsapp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mais': {
      id: '/_authenticated/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof AuthenticatedMaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bi': {
      id: '/_authenticated/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedBiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aura-ia': {
      id: '/_authenticated/aura-ia'
      path: '/aura-ia'
      fullPath: '/aura-ia'
      preLoaderRoute: typeof AuthenticatedAuraIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/': {
      id: '/_authenticated/whatsapp/'
      path: '/'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof AuthenticatedWhatsappIndexRouteImport
      parentRoute: typeof AuthenticatedWhatsappRoute
    }
    '/_authenticated/marketing/': {
      id: '/_authenticated/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AuthenticatedMarketingIndexRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/equipe/': {
      id: '/_authenticated/equipe/'
      path: '/'
      fullPath: '/equipe/'
      preLoaderRoute: typeof AuthenticatedEquipeIndexRouteImport
      parentRoute: typeof AuthenticatedEquipeRoute
    }
    '/_authenticated/bi/': {
      id: '/_authenticated/bi/'
      path: '/'
      fullPath: '/bi/'
      preLoaderRoute: typeof AuthenticatedBiIndexRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/aura-ia/': {
      id: '/_authenticated/aura-ia/'
      path: '/'
      fullPath: '/aura-ia/'
      preLoaderRoute: typeof AuthenticatedAuraIaIndexRouteImport
      parentRoute: typeof AuthenticatedAuraIaRoute
    }
    '/_authenticated/whatsapp/templates': {
      id: '/_authenticated/whatsapp/templates'
      path: '/templates'
      fullPath: '/whatsapp/templates'
      preLoaderRoute: typeof AuthenticatedWhatsappTemplatesRouteImport
      parentRoute: typeof AuthenticatedWhatsappRoute
    }
    '/_authenticated/whatsapp/config': {
      id: '/_authenticated/whatsapp/config'
      path: '/config'
      fullPath: '/whatsapp/config'
      preLoaderRoute: typeof AuthenticatedWhatsappConfigRouteImport
      parentRoute: typeof AuthenticatedWhatsappRoute
    }
    '/_authenticated/whatsapp/$id': {
      id: '/_authenticated/whatsapp/$id'
      path: '/$id'
      fullPath: '/whatsapp/$id'
      preLoaderRoute: typeof AuthenticatedWhatsappIdRouteImport
      parentRoute: typeof AuthenticatedWhatsappRoute
    }
    '/_authenticated/servicos/$id': {
      id: '/_authenticated/servicos/$id'
      path: '/$id'
      fullPath: '/servicos/$id'
      preLoaderRoute: typeof AuthenticatedServicosIdRouteImport
      parentRoute: typeof AuthenticatedServicosRoute
    }
    '/_authenticated/marketing/jornadas': {
      id: '/_authenticated/marketing/jornadas'
      path: '/jornadas'
      fullPath: '/marketing/jornadas'
      preLoaderRoute: typeof AuthenticatedMarketingJornadasRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/ia': {
      id: '/_authenticated/marketing/ia'
      path: '/ia'
      fullPath: '/marketing/ia'
      preLoaderRoute: typeof AuthenticatedMarketingIaRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/$id': {
      id: '/_authenticated/marketing/$id'
      path: '/$id'
      fullPath: '/marketing/$id'
      preLoaderRoute: typeof AuthenticatedMarketingIdRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/financeiro/fluxo': {
      id: '/_authenticated/financeiro/fluxo'
      path: '/fluxo'
      fullPath: '/financeiro/fluxo'
      preLoaderRoute: typeof AuthenticatedFinanceiroFluxoRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/cfo': {
      id: '/_authenticated/financeiro/cfo'
      path: '/cfo'
      fullPath: '/financeiro/cfo'
      preLoaderRoute: typeof AuthenticatedFinanceiroCfoRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/estoque/preditivo': {
      id: '/_authenticated/estoque/preditivo'
      path: '/preditivo'
      fullPath: '/estoque/preditivo'
      preLoaderRoute: typeof AuthenticatedEstoquePreditivoRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/$id': {
      id: '/_authenticated/estoque/$id'
      path: '/$id'
      fullPath: '/estoque/$id'
      preLoaderRoute: typeof AuthenticatedEstoqueIdRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/equipe/$id': {
      id: '/_authenticated/equipe/$id'
      path: '/$id'
      fullPath: '/equipe/$id'
      preLoaderRoute: typeof AuthenticatedEquipeIdRouteImport
      parentRoute: typeof AuthenticatedEquipeRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/bi/servicos': {
      id: '/_authenticated/bi/servicos'
      path: '/servicos'
      fullPath: '/bi/servicos'
      preLoaderRoute: typeof AuthenticatedBiServicosRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/bi/preditivo': {
      id: '/_authenticated/bi/preditivo'
      path: '/preditivo'
      fullPath: '/bi/preditivo'
      preLoaderRoute: typeof AuthenticatedBiPreditivoRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/bi/clientes': {
      id: '/_authenticated/bi/clientes'
      path: '/clientes'
      fullPath: '/bi/clientes'
      preLoaderRoute: typeof AuthenticatedBiClientesRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/aura-ia/conselho': {
      id: '/_authenticated/aura-ia/conselho'
      path: '/conselho'
      fullPath: '/aura-ia/conselho'
      preLoaderRoute: typeof AuthenticatedAuraIaConselhoRouteImport
      parentRoute: typeof AuthenticatedAuraIaRoute
    }
    '/_authenticated/aura-ia/chat': {
      id: '/_authenticated/aura-ia/chat'
      path: '/chat'
      fullPath: '/aura-ia/chat'
      preLoaderRoute: typeof AuthenticatedAuraIaChatRouteImport
      parentRoute: typeof AuthenticatedAuraIaRoute
    }
  }
}

interface AuthenticatedAuraIaRouteChildren {
  AuthenticatedAuraIaChatRoute: typeof AuthenticatedAuraIaChatRoute
  AuthenticatedAuraIaConselhoRoute: typeof AuthenticatedAuraIaConselhoRoute
  AuthenticatedAuraIaIndexRoute: typeof AuthenticatedAuraIaIndexRoute
}

const AuthenticatedAuraIaRouteChildren: AuthenticatedAuraIaRouteChildren = {
  AuthenticatedAuraIaChatRoute: AuthenticatedAuraIaChatRoute,
  AuthenticatedAuraIaConselhoRoute: AuthenticatedAuraIaConselhoRoute,
  AuthenticatedAuraIaIndexRoute: AuthenticatedAuraIaIndexRoute,
}

const AuthenticatedAuraIaRouteWithChildren =
  AuthenticatedAuraIaRoute._addFileChildren(AuthenticatedAuraIaRouteChildren)

interface AuthenticatedBiRouteChildren {
  AuthenticatedBiClientesRoute: typeof AuthenticatedBiClientesRoute
  AuthenticatedBiPreditivoRoute: typeof AuthenticatedBiPreditivoRoute
  AuthenticatedBiServicosRoute: typeof AuthenticatedBiServicosRoute
  AuthenticatedBiIndexRoute: typeof AuthenticatedBiIndexRoute
}

const AuthenticatedBiRouteChildren: AuthenticatedBiRouteChildren = {
  AuthenticatedBiClientesRoute: AuthenticatedBiClientesRoute,
  AuthenticatedBiPreditivoRoute: AuthenticatedBiPreditivoRoute,
  AuthenticatedBiServicosRoute: AuthenticatedBiServicosRoute,
  AuthenticatedBiIndexRoute: AuthenticatedBiIndexRoute,
}

const AuthenticatedBiRouteWithChildren = AuthenticatedBiRoute._addFileChildren(
  AuthenticatedBiRouteChildren,
)

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedEquipeRouteChildren {
  AuthenticatedEquipeIdRoute: typeof AuthenticatedEquipeIdRoute
  AuthenticatedEquipeIndexRoute: typeof AuthenticatedEquipeIndexRoute
}

const AuthenticatedEquipeRouteChildren: AuthenticatedEquipeRouteChildren = {
  AuthenticatedEquipeIdRoute: AuthenticatedEquipeIdRoute,
  AuthenticatedEquipeIndexRoute: AuthenticatedEquipeIndexRoute,
}

const AuthenticatedEquipeRouteWithChildren =
  AuthenticatedEquipeRoute._addFileChildren(AuthenticatedEquipeRouteChildren)

interface AuthenticatedEstoqueRouteChildren {
  AuthenticatedEstoqueIdRoute: typeof AuthenticatedEstoqueIdRoute
  AuthenticatedEstoquePreditivoRoute: typeof AuthenticatedEstoquePreditivoRoute
}

const AuthenticatedEstoqueRouteChildren: AuthenticatedEstoqueRouteChildren = {
  AuthenticatedEstoqueIdRoute: AuthenticatedEstoqueIdRoute,
  AuthenticatedEstoquePreditivoRoute: AuthenticatedEstoquePreditivoRoute,
}

const AuthenticatedEstoqueRouteWithChildren =
  AuthenticatedEstoqueRoute._addFileChildren(AuthenticatedEstoqueRouteChildren)

interface AuthenticatedFinanceiroRouteChildren {
  AuthenticatedFinanceiroCfoRoute: typeof AuthenticatedFinanceiroCfoRoute
  AuthenticatedFinanceiroFluxoRoute: typeof AuthenticatedFinanceiroFluxoRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
}

const AuthenticatedFinanceiroRouteChildren: AuthenticatedFinanceiroRouteChildren =
  {
    AuthenticatedFinanceiroCfoRoute: AuthenticatedFinanceiroCfoRoute,
    AuthenticatedFinanceiroFluxoRoute: AuthenticatedFinanceiroFluxoRoute,
    AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  }

const AuthenticatedFinanceiroRouteWithChildren =
  AuthenticatedFinanceiroRoute._addFileChildren(
    AuthenticatedFinanceiroRouteChildren,
  )

interface AuthenticatedMarketingRouteChildren {
  AuthenticatedMarketingIdRoute: typeof AuthenticatedMarketingIdRoute
  AuthenticatedMarketingIaRoute: typeof AuthenticatedMarketingIaRoute
  AuthenticatedMarketingJornadasRoute: typeof AuthenticatedMarketingJornadasRoute
  AuthenticatedMarketingIndexRoute: typeof AuthenticatedMarketingIndexRoute
}

const AuthenticatedMarketingRouteChildren: AuthenticatedMarketingRouteChildren =
  {
    AuthenticatedMarketingIdRoute: AuthenticatedMarketingIdRoute,
    AuthenticatedMarketingIaRoute: AuthenticatedMarketingIaRoute,
    AuthenticatedMarketingJornadasRoute: AuthenticatedMarketingJornadasRoute,
    AuthenticatedMarketingIndexRoute: AuthenticatedMarketingIndexRoute,
  }

const AuthenticatedMarketingRouteWithChildren =
  AuthenticatedMarketingRoute._addFileChildren(
    AuthenticatedMarketingRouteChildren,
  )

interface AuthenticatedServicosRouteChildren {
  AuthenticatedServicosIdRoute: typeof AuthenticatedServicosIdRoute
}

const AuthenticatedServicosRouteChildren: AuthenticatedServicosRouteChildren = {
  AuthenticatedServicosIdRoute: AuthenticatedServicosIdRoute,
}

const AuthenticatedServicosRouteWithChildren =
  AuthenticatedServicosRoute._addFileChildren(
    AuthenticatedServicosRouteChildren,
  )

interface AuthenticatedWhatsappRouteChildren {
  AuthenticatedWhatsappIdRoute: typeof AuthenticatedWhatsappIdRoute
  AuthenticatedWhatsappConfigRoute: typeof AuthenticatedWhatsappConfigRoute
  AuthenticatedWhatsappTemplatesRoute: typeof AuthenticatedWhatsappTemplatesRoute
  AuthenticatedWhatsappIndexRoute: typeof AuthenticatedWhatsappIndexRoute
}

const AuthenticatedWhatsappRouteChildren: AuthenticatedWhatsappRouteChildren = {
  AuthenticatedWhatsappIdRoute: AuthenticatedWhatsappIdRoute,
  AuthenticatedWhatsappConfigRoute: AuthenticatedWhatsappConfigRoute,
  AuthenticatedWhatsappTemplatesRoute: AuthenticatedWhatsappTemplatesRoute,
  AuthenticatedWhatsappIndexRoute: AuthenticatedWhatsappIndexRoute,
}

const AuthenticatedWhatsappRouteWithChildren =
  AuthenticatedWhatsappRoute._addFileChildren(
    AuthenticatedWhatsappRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAuraIaRoute: typeof AuthenticatedAuraIaRouteWithChildren
  AuthenticatedBiRoute: typeof AuthenticatedBiRouteWithChildren
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRouteWithChildren
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRouteWithChildren
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRouteWithChildren
  AuthenticatedMaisRoute: typeof AuthenticatedMaisRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRouteWithChildren
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRouteWithChildren
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAuraIaRoute: AuthenticatedAuraIaRouteWithChildren,
  AuthenticatedBiRoute: AuthenticatedBiRouteWithChildren,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRouteWithChildren,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRouteWithChildren,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRouteWithChildren,
  AuthenticatedMaisRoute: AuthenticatedMaisRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRouteWithChildren,
  AuthenticatedServicosRoute: AuthenticatedServicosRouteWithChildren,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
